edit_uri: edit/main/docs/
markdown_extensions:
- admonition
- attr_list
- codehilite
- md_in_html
- meta
- pymdownx.highlight:
    use_pygments: true
- pymdownx.superfences
- pymdownx.tabbed
nav:
- Home: index.md
- API Reference:
  - public_data.md
  - grid_trading.md
  - block_trading.md
  - trading_data.md
  - status.md
  - savings.md
  - earn.md
  - funding.md
  - recurring_buy.md
  - subaccount.md
  - trade.md
  - market_data.md
  - convert.md
  - account.md
  - copy_trading.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          heading_level: 2
          show_bases: true
          show_category_heading: true
          show_object_full_path: false
          show_root_heading: true
          show_source: false
repo_url: https://github.com/nicelgueta/pyokx
site_name: pyokx
theme:
  favicon: img/favicon.ico
  font:
    code: Source Code Pro
    text: Inter
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - accent: black
    media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - accent: black
    media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
watch:
- pyokx/
- README.md
